# Build a universal wheel and store it as an artifact

name: Build wheel

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-wheel:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build
      - name: Build wheel and sdist
        run: |
          python -m build
      - name: Archive wheel as artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel-artifact
          path: dist/*.whl
