# Build and upload a wheel. No tests run, this should be
# handled via a larger workflow

name: Upload wheel to PyPI Test

on:
  workflow_call:

jobs:
  publish-pypi-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
    - name: Build package
      run: python -m build
    - name: Debug checks
      run: ls -l dist/
    - name: Debug publish with twine
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: echo twine upload --repository testpypi -u __token__ -p $PYPI_TOKEN dist/*.whl
    - name: Publish with twine
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: twine upload --repository testpypi -u __token__ -p $PYPI_TOKEN dist/*.whl
