name: Upload to PyPI Test

on:
  push:
    tags:
      - v*

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
  unit-tests-multiplatform:
    uses: ./.github/workflows/unit-tests-multiplatform.yml
    needs: [code-quality]
  publish-pypi-test:
    needs: [unit-tests-multiplatform]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
    - name: Build package
      run: python -m build
    - name: Publish package
      run: twine upload --repository testpypi -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*.whl
