name: Upload wheel to PyPI Test

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  publish-pypi-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
    - name: Build package
      run: python -m build
    - name: Debug check
      run: echo twine upload --repository testpypi -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*.whl
    # - name: Publish package
      # run: twine upload --repository testpypi -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*.whl
