# Run unit tests on ubuntu against multiple python versions
# Use this for regular QA (pull requests, main branch)

name: Regular tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    needs: [code-quality]
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.7", "3.8", "3.9", "3.10"]
