# Release workflow. Run basic QA, build and test the universal wheel on many
# platforms, then publish to pypi

name: Release

on:
  push:
    tags:
      - v*

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
  test-wheels:
    uses: ./.github/workflows/test-wheels.yml
    needs: [code-quality]
  publish-pypi-test:
    uses: ./.github/workflows/publish-pypi-test.yml
    needs: [test-wheels]
