name: Sync current

on:
  push:
    branches:
      - main

jobs:
  sync-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'current'
      - name: Fast forward
        run: |
          git fetch origin main
          git merge --ff-only origin/main
      - name: Push
        run: |
          git push origin current
