# Run the unit tests against several pythons and platforms
# using a built wheel to install the package.

name: Test wheels

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test-wheels:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build
      - name: Build wheel
        run: |
          python -m build
      - name: Fetch dependencies
        run: |
          pip wheel -f dist --wheel-dir=dist hatch-demo-simon-bowly
      - name: Install wheel
        run: |
          python -m pip install -f dist --no-index --only-binary=:all: hatch-demo-simon-bowly
      - name: Test import
        run: |
          python -c "import hatch_demo_simon_bowly"
      - name: Run unittest
        run: |
          python -m unittest discover -b
