# Run the unit tests against several pythons and platforms
# using a pre-built wheel artifact to install the package.

name: Test wheel

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build-wheel:

    uses: ./.github/workflows/build-wheel.yml

  test-wheels:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: File listing
        run: ls dist/
      - name: Fetch built wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel-artifact
      - name: File listing
        run: ls dist/
      - name: Fetch dependencies for offline install
        run: |
          pip wheel --wheel-dir=dist pandas
      - name: File listing
        run: ls dist/
      - name: Install wheel
        run: |
          python -m pip install -f dist --no-index --only-binary=:all: hatch-demo-simon-bowly
      - name: Test import
        run: |
          python -c "import hatch_demo_simon_bowly"
      - name: Run unittest
        run: |
          python -m unittest discover -b
