# Run the unit tests against several pythons and platforms

name: Unit tests (multi-platform)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit-test-multiplatform:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          python -m pip install .
      - name: Run unittest
        run: python -m unittest
