# Run the unit tests against given OSs and Pythons
# Needs to have a matrix to work ... but it seems if this run has more
# than one matrix replica, you get duplicates when it is used with
# larger matrices. So just included python3.7 here.
# Has no triggers
# matrix.python is required from the caller

name: Python unit tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Install dependencies
        run: |
          python -m pip install .
      - name: Run unittest
        run: python -m unittest
